name: Build Windows

env:
  BuildSolution: PopCoreml.visualstudio\PopCoreml.sln
  BuildPlatform: x64
  BuildConfiguration: Release
# would be nice to extract this from visual studio
  BuildDirectory: PopCoreml.visualstudio\x64\Release

on: 
  push:
    branches:
      - master

jobs:
  buildwindows:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: compile
# https://github.community/t5/GitHub-Actions/How-to-build-project-targeting-Net35-with-GitHub-Actions/td-p/36191
# set <--- list env vars
      run: |
          set
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Current\Bin\MSBuild.exe" %BuildSolution% /property:Configuration=%BuildConfiguration% /property:Platform=%BuildPlatform%
      shell: cmd
      
    - name: List artifacts
      run: |
        ls .
        ls PopCoreml.visualstudio
        ls $Env:BuildDirectory
    
    # do not use env here: ##[error]Path does not exist d:\a\PopH264\PopH264\$Env:GITHUB_WORKSPACE\PopH264.visualstudio\Debug
    - uses: actions/upload-artifact@v1
      with:
        name: PopCoreml.dll
        path: ${{env.BuildDirectory}}\PopCoreml.dll
    - uses: actions/upload-artifact@v1
      with:
        name: PopCoreml.lib
        path: ${{env.BuildDirectory}}\PopCoreml.lib
    - uses: actions/upload-artifact@v1
      with:
        name: PopCoreml.h
        path: Source/PopCoreml.h
        
#PopH264.visualstudio\Debug\PopH264.dll
